### ISSUE TITLE
Some tests are fialed sometimes

### ISSUE THREAD

**Issue by alirizaadiyahsi** [alirizaadiyahsi/Nucleus#28]
Message:

> System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
> Could not load type 'Castle.Proxies.UserProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Stacktrace:

> Result StackTrace:	
> at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 69
>    at Nucleus.Application.ApplicationServiceCollectionExtensions.ConfigureNucleusApplication(IServiceCollection services) in D:\GitHub\Nucleus\src\Nucleus.Application\ApplicationServiceCollectionExtensions.cs:line 13
>    at Nucleus.Web.Api.Startup.ConfigureServices(IServiceCollection services) in D:\GitHub\Nucleus\src\Nucleus.Web.Api\Startup.cs:line 28
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
>    at Nucleus.Tests.Shared.TestBase.get_TestServer() in D:\GitHub\Nucleus\test\Nucleus.Tests.Shared\TestBase.cs:line 24
>    at Nucleus.Tests.Web.Api.ActionFilters.UnitOfWorkFilterTest.Should_Not_UnitOfWork_Action_Filter_Save_Changes_Except_Post() in D:\GitHub\Nucleus\test\Nucleus.Tests.Web.Api\ActionFilters\UnitOfWorkFilterTest.cs:line 81
> --- End of stack trace from previous location where exception was thrown ---
> Result Message:	
> System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
> Could not load type 'Castle.Proxies.UserProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
>

**Comment by alirizaadiyahsi** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/28
